### PR TITLE
Recoded the whole thing, add migrate feature

### PR DESCRIPTION
**Pull request by math2001**
hello!

This plugin is really useful! So much that I made it work with [BetterSnippetManager][].

If you have a look at the code of this PR, everything has changed:

- Snippets are converted using a OOP system. There's a class, you give it the filename, call `convert()`, and it writes the "opposite" file with the converted content. (so it goes both ways)
- And then, everything you said in your readme is implemented (convert on save, clean containing repo, etc)

So, let me know what you think!

Matt

[BetterSnippetManager]: https://github.com/math2001/BetterSnippetManager

### CODE REVIEW

**Comment by Kristinita** [comment]
@bobthecow , please, review this pull request.

Thanks.

**Comment by Kristinita** [comment]
@bobthecow , ping.

**Comment by Kristinita** [comment]
@math2001, I reproduce the problem in fresh Sublime Text version without plugins and user settings.

### 1. Steps to reproduce

I install your fork → I restart Sublime Text → `Preferences` → `Browse Packages…` → `User` → I create `snippets` folder → I create file `choco-zip.sublime-snippet` ([**on gist**](https://gist.github.com/Kristinita/6c14fa1c2570ef284b0c0a448ca6fae8)) → <kbd>Ctrl+Shift+P</kbd> → `SaneSnippets: Migrate` → I get stack trace, snippet don't convert for me to `sane-snippets`.

```python
command: sane_snippets {"action": "migrate"}
Traceback (most recent call last):
  File "D:\Sublime Text Build 3126 x64 For Debug\sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "sane_snippets in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 85, in run
  File "sane_snippets in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 61, in migrate_action
  File "sane_snippets_tools in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 86, in convert
  File "sane_snippets_tools in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 50, in parse
  File "./python3.3/xml/etree/ElementTree.py", line 1242, in parse
  File "./python3.3/xml/etree/ElementTree.py", line 1730, in parse
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

### 2. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126


Thanks.

**Comment by math2001** [comment]
I opened the issue tracker on my fork, it'll be a better place to talk about this bug. Can you please open an issue with the same message (perfect as usual 😄)

**Comment by TheSecEng** [comment]
@bobthecow Any idea if this will be merged? Are you still maintaining this? If not, would you be open too transferring it to SublimeText/ Organization so we can maintain it there?

**Comment by FichteFoll** [comment]
I just saw I didn't watch this repository for some reason, despite having probably authored most if its current contents.

I haven't reviewed this PR yet, but I would appreciate if we could maintain it in the future somehow, even if @bobthecow isn't able to do anymore. I could offer forking the package to the @SublimeText org if @bobthecow remains unavailable in the next few weeks, and would also take maintainership of the package wrt reviweing this PR, merging it and applying some changes on top of it. There are definitely a lot of improvements to be made compared to current `master` and I've had todo items on it for years, such as generating the snippet backlog in a background thread and using `sublime_lib.ResourcePath`.

**Comment by bobthecow** [comment]
I'm happy to add you as a maintainer @FichteFoll, or to move this repo over to @SublimeText. Whatever you think makes sense :)

**Comment by FichteFoll** [comment]
I suggest moving it to the org. Since you are already a member, I don't need to prepare anything either. Github does redirects on the URLs, even for what Package Control uses, but I'll update the URL and package metadata there later, once I updated the package and likely removed ST2 support. Maybe some of the new ST4000 API could be useful as well.

**Comment by bobthecow** [comment]
@FichteFoll it's transferred!

**Comment by FichteFoll** [comment]
Awesome, thanks. I'd like to rename the repo to "SaneSnippets" as well, since it's already namespaced by the org now.

**Comment by FichteFoll** [comment]
@math2001, I just took a more thoroguh look at the code and unfortunately I won't be merging this, as I believe some of the design choices to be wrong and suboptimal. I will take inspiration where it makes sense, but I will otherwise refactor and rewrite most of it from the current base. Just FYI.

I also renamed the repo.

**Comment by FichteFoll** [comment]
Opened #15.

**Pull request closed without merging**
